import Head from 'next/head'
import Image from 'next/image'
import CenterLayout from "../components/centerLayout";
import RefreshButton from '../components/refreshButton';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CenterLayout>
      <div className="flex-1">
        <div className="content-center">
          <h1 className="m-4 text-center text-xl "> Air Stats</h1>
          <RefreshButton />
        </div>
        </div>
      </CenterLayout>
      

    </div>
  )
}
